name: Tag Update
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "database.json"
      - "database.msgpack"
  workflow_dispatch:

jobs:
  tag-update:
    name: "Tag Latest Commit"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Prepare: Checkout"
        uses: actions/checkout@v4

      - name: "Prepare: Setup Rokit"
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: "Prepare: Git Config"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global credential.helper "!f() { sleep 1; echo username=x-access-token; echo password=$GITHUB_TOKEN; }; f"

      - name: "Run: Tag Latest Commit"
        run: |
          lune run tag-latest-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
